pub const WORKSPACE_MAX_MEMORY_MB: i32 = 2048; 
pub const WORKSPACE_MAX_STORAGE_GB: i32 = 10;  

pub const DEFAULT_EMAIL_NOTIFICATIONS: bool = true;

pub const ACCESS_TOKEN_EXPIRATION_SECONDS: i64 = 900; 
pub const REFRESH_TOKEN_EXPIRATION_DAYS: i64 = 7;